### ISSUE TITLE
Installation instruction without docker ?

### ISSUE THREAD

**Issue by lapineige** [MerginMaps/mergin#104]
Hello,

Is there any installation documentation for a non-docker ("native install") version ?
I couldn't find instructions for such a installation.

Thank you.

**Comment by PeterPetrik** [comment]
Hi, you can look at developer documentation https://github.com/MerginMaps/mergin/blob/master/development.md or try to duplicate steps in Dockerfiles locally: https://github.com/MerginMaps/mergin/blob/master/server/Dockerfile and https://github.com/MerginMaps/mergin/blob/master/web-app/Dockerfile. If you are not experienced (server) developer, I would not recommend this path.

**Comment by lapineige** [comment]
> If you are not experienced (server) developer, I would not recommend this path.

I'm not, but for an in integration in Yunohost packaging this is (almost) mandatory (and easier).


I'll give it a try, thank you :slightly_smiling_face:
I see a lot of docker commands in this version, if I set up Redis and PostgreSQL by my-self (actually, Yunohost automates it), is there any special config to apply ?
