### ISSUE TITLE
Connect Android/Iphone MerginMaps App to local MerginMaps Server

### ISSUE THREAD

**Issue by abodsalas** [MerginMaps/mergin#106]
Hi.
Following your instructions, I have been able to get the MerginMaps Server run on an Ubuntu 22.04 machine.
I can connect the QGIS plugin correctly , upload, download and Sync.

However I cannot find how to configure my local MerginMaps Server on the Android App.
Is there an option?

I know that the Input App is also open source (https://github.com/MerginMaps/input), but I don't know where one can chage de IP and port of the default MergiMaps server.

Is there a way to do this?

**Comment by tomasMizera** [comment]
Hi @abodsalas,
you can connect to a custom hosted server from the mobile app like this:

- go to login page
- hit the pencil icon on the bottom
- change the url (+ include leading slash)
- hit the pencil icon again

For similar questions, please join our community Slack - you will get response much quicker :) https://merginmaps.com/community/join

**Comment by abodsalas** [comment]
Thank you very much.
The icon was hard to see.
![image](https://github.com/MerginMaps/mergin/assets/54449155/e6fc654f-988e-4dc3-9fb7-e11402236704)
