### ISSUE TITLE
Feature request/Enhancement: capability for merging features

### ISSUE THREAD

**Issue by rosaguilar** [MerginMaps/mergin#108]
Thanks for the amazing app. It would be nice to have the possibility of merging features, for example: selecting them from the features list and then merge. The attribute logic could be very simple: the first or the last dictates the attributes. Cheers

**Comment by tomasMizera** [comment]
Hello @rosaguilar, thank you for your request. I forwarded it to our wishlist page here: https://wishlist.merginmaps.com/p/add-an-option-to-merge-features You can vote for it and track its progress there.
