### ISSUE TITLE
href of top right logo miss a / in url

### ISSUE THREAD

**Issue by nicogodet** [MerginMaps/mergin#14]
![image](https://user-images.githubusercontent.com/39594821/124561280-00f00280-de3e-11eb-8ea3-5ef8b92c6aea.png)

![image](https://user-images.githubusercontent.com/39594821/124561243-f6356d80-de3d-11eb-8aab-cee881a6d2bc.png)

It leads to a blank page.

**Comment by varmar05** [comment]
Fixed in 2023.2.0 to default route (`/dashboard`).
