### ISSUE TITLE
Install on windows looking for wrong version of pygeodiff.dll

### ISSUE THREAD

**Issue by bogind** [MerginMaps/mergin#31]
After successful install on windows 10, Mergin fails to create new projects.  
Version 0.8.6 of pygeodiff only created `pygeodiff-0.8.6-python-win32.dll` in the `env/Lib/site-packages/pygeodiff` folder when Mergin is looking for `pygeodiff-0.8.6-python.dll`.
This seems to be [an old pygeodiff](https://github.com/lutraconsulting/geodiff/issues/25) issue but which should have been fixed.

Got around it by copying `pygeodiff-0.8.6-python-win32.dll` and renaming to `pygeodiff-0.8.6-python.dll`, not sure this is the correct method or should Mergin be used like that.

  `WARNING:root:HTTP 400: Failed to initialize project: Unable to locate GeoDiff library, tried C:\Users\User\.virtualenvs\server-jpXDwBY0\Lib\site-packages\pygeodiff\pygeodiff-0.8.6-python.dll and geodiff on system.`
![image](https://user-images.githubusercontent.com/26594971/161685485-0f836f7b-eb1e-4a0c-bb0c-70db88823720.png)

**Comment by PeterPetrik** [comment]
@varmar05 can you please confirm if it is good workaround?

**Comment by PeterPetrik** [comment]
Can you please test in version 2023.2?

**Comment by bogind** [comment]
Unfortunately I don't have access to that system anymore.
I could try installing on another computer, but I'm not sure that will have the same results.

**Comment by PeterPetrik** [comment]
ok no problem, lets close it in the meantime.
