### ISSUE TITLE
Conflicting licensing terms in file headers with AGPL

### ISSUE THREAD

**Issue by rouault** [MerginMaps/mergin#7]
Many source files have "All rights reserved. Do not distribute without the express permission of the author" in their header (
https://github.com/lutraconsulting/mergin/search?q=All+rights+reserved ) which must predate the AGPL licensing. They should be likely be replaced with a reference to AGPL instead

**Comment by PeterPetrik** [comment]
Solved now via https://github.com/MerginMaps/mergin/commit/99e96f5ec56fa42186fc33a3c21c5c4a290dc20e
