### ISSUE TITLE
Project access permissions for users

### ISSUE THREAD

**Issue by peterisdaknis** [MerginMaps/mergin#81]
Hello!

I'm running four projects on my instance and some of those projects are not related to others and may have some sensitive data. Just learned, that all users can see and download all projects, even if projects are not shared with them. Would be very useful, if that is possible only for users, who are given access to the exact project, otherwise, I have to run multiple instances of Mergin. Or is there another way? On the "real" MerginMaps server this was solved through workspaces, but I don't see this feature here.

**Comment by varmar05** [comment]
Hi @peterisdaknis, you can try to set `GLOBAL_READ=false` (https://merginmaps.com/docs/dev/mergince/#data-synchronisation-and-user-management) which means that all your users are kind of guests who do not have access to anything. As admin you can then assign permissions per project.  

If you happen to have multiple user groups and projects I think Mergin Maps Enterprise Edition would be the option. It uses workspaces the same way as our cloud service.
