### ISSUE TITLE
Manage User

### ISSUE THREAD

**Issue by katagen** [MerginMaps/mergin#9]
Where can we manage the users?
I created different users for test. How can I delete them?

What I found also "strange", is that I have no "local" volume with this data in docker!?! We only have the projects.

It will be problematic if I want to update the container, no? I will lose all the users? Or am I wrong?

**Comment by sp1ritnsk** [comment]
> What I found also "strange", is that I have no "local" volume with this data in docker!?! We only have the projects.
> 
> It will be problematic if I want to update the container, no? I will lose all the users? Or am I wrong?

Yes DB data is lost after `docker-compose down`. I added 
`volumes:
      - ./postgres-data:/var/lib/postgresql/data`
to db section of services in `docker-compose.yml` and everything was in place after `down` and `up` again.

**Comment by katagen** [comment]
Perfect, but did you also changed the permissions to that folder? Or is it not necessary?

**Comment by varmar05** [comment]
It was added to docker-compose file. And guide to run containers is now here https://merginmaps.com/docs/dev/mergince/#start-docker-containers.
